DROP TABLE IF NOT EXIXTS SALESMAN;
CREATE TABLE IF EXISTS SALESMAN (
    SALESMAN_ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    COMMISSION REAL
);

INSERT INTO SALESMAN(SALESMAN_ID, NAME, CITY, COMMISION) VALUES