DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_NAME TEXT,
    CATAGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_NAME, CATAGORY_ID, UNIT, PRICE) VALUES 

("1", "CHAIS", "1", "1", "10 BOXES*20 BAGS", 18),
("2", "CHANG", "1", "1", "24-12 OZ JARS", 19),
("3", "ANISEED SYRUP", "1", "2", "12-550 ML BOTTLES", 10),
("4", "CHEF ANTON SESONINGS", "1", "2", "46-8 OZ JARS", 22),
("5", "CHEF ANTON MIX", "1", "2", "36 BOXES", 22.35);

SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS;

SELECT SUM(PRICE) AS TOTAL_PRICE
FROM PRODUCTS;