DROP TABLE IF EXISTS SALES;
CREATE TABLE IF NOT EXISTS SALES (
    ID INT PRIMARY KEY,
    ITEM VARCHAR(50),
    CATEGORY VARCHAR(50),
    PRICE INT,
    QUANTITY INT,
    TOTAL INT
);

INSERT INTO SALES (ID, ITEM, CATEGORY, PRICE, QUANTITY, TOTAL)
VALUES
(1, 'CHOCOLATE', 'FOOD', 50, 10, 500),
(2, 'NOTEBOOK', 'STATIONERY', 30, 20, 600),
(3, 'JUICE', 'DRINK', 40, 15, 600),
(4, 'PEN', 'STATIONERY', 10, 50, 500),
(5, 'COFFEE', 'DRINK', 60, 5, 300),
(6, 'COOKIES', 'FOOD', 20, 30, 600);

SELECT * FROM SALES;

SELECT ITEM, TOTAL FROM SALES;

SELECT SUM(TOTAL) AS SHOP_INCOME FROM SALES;

SELECT MIN(TOTAL) AS SMALLEST_SALE FROM SALES;

SELECT MAX(TOTAL) AS BIGGEST_SALE FROM SALES;

SELECT * FROM SALES WHERE CATEGORY = 'STATIONERY' AND TOTAL > 500;

SELECT * FROM SALES WHERE ITEM = 'CHOCOLATE' OR TOTAL = 600;

UPDATE SALES 
SET QUANTITY = 25, TOTAL = PRICE * 25 
WHERE ITEM = 'NOTEBOOK';

UPDATE SALES 
SET PRICE = 70, TOTAL = 70 * QUANTITY 
WHERE ITEM = 'COFFEE';

DELETE FROM SALES WHERE ITEM = 'PEN';

SELECT * FROM SALES;