DROP TABLE IF EXISTS NOBLE_WINNERS;
CREATE TABLE IF NOT EXISTS NOBLE_WINNERS (
    YEAR INTERGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBLE_WINNERS (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
(1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HAMMILTON', 'SWEDEN', 'LINGUIST'),
(1972, 'LITERATURE', 'BENNARD KELSON', 'GERMANY', 'ECONOMIST'),
(1973, 'ECONOMICS', 'JOSEPH', 'RUSSIAN', 'ECONOMIST'),
(1980, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
(1981, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
(1975, 'PHYSIOLOGY', 'HANNAH', 'HANGARY', 'SCIENTIST'),
(1975, 'PHYSIOLOGY', 'PETER', 'CHILE', 'SCIENTIST');

SELECT *
FROM NOBLE_WINNERS
WHERE SUBJECT NOT LIKE 'P%';